[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
evm_version = "prague"

[dependencies]
forge-std = "1.9.7"
"@openzeppelin-contracts" = "5.3.0"
"@openzeppelin-contracts-upgradeable" = "5.3.0"
openzeppelin-foundry-upgrades = "0.4.0"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
