[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
solc_version = "0.8.22"
optimizer = true
optimizer_runs = 200
ast = true
build_info = true
extra_output = ["storageLayout"]

[dependencies]
forge-std = "1.9.7"
"@openzeppelin-contracts" = "5.3.0"
"@openzeppelin-contracts-upgradeable" = "5.3.0"
openzeppelin-foundry-upgrades = { version = "0.4.0", git = "https://github.com/ericglau/openzeppelin-foundry-upgrades/", tag = "v0.4.8" }
"@pythnetwork-pyth-sdk-solidity" = "4.2.0"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
